#ifndef GAME_DATA_HPP
#define GAME_DATA_HPP

#include <cstdint>
#include <filesystem>

#include "data/BlockRegistry.hpp"
#include "lib/json.hpp"
#include <map>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

// Version-specific game data loaded at startup from gamedata/ (generated by tools/update_gamedata.py), then
// gamedata/overrides.json (written by hand) applied on top:
//   {
//     "blocks":      { "minecraft:obsidian": { "destroy_time": 10, "light_emission": 7 },
//                      "minecraft:rose_bush": { "shape": "single" } },
//     "items":       { "minecraft:diamond_sword": { "attack_damage": 10 } },
//     "block_items": { "minecraft:stick": "minecraft:torch" }
//   }
// Block keys: any BlockProperties or StateProperties field below, by its JSON name (state ones apply to every state).
// Item keys: any ItemProperties field below, by its JSON name.
//
// Static registries (block, item, entity_type...) have ids fixed in the client.
// Synced registries (biome, dimension_type, enchantment...) are sent in Registry Data: an entry's id is its position in that packet.
class GameData {
  public:
	struct Registry {
		std::string							 name;
		std::vector<std::string>			 entries; // Index == network id
		std::unordered_map<std::string, int> ids;
	};

	// Blocks spanning two positions: one state per position, linked by a property
	enum class Shape {
		Single,
		DoubleHeight, // half=lower below, half=upper above (doors, tall plants)
		DoubleLength  // part=foot, part=head one block further in the facing direction (beds)
	};

	// Per block, from the game code
	struct BlockProperties {
		float destroyTime		  = 0; // Seconds to break by hand; -1 = unbreakable ("destroy_time")
		float explosionResistance = 0; // "explosion_resistance"
		float friction			  = 0.6f;
		float speedFactor		  = 1; // Walking speed multiplier ("speed_factor": soul sand, honey)
		float jumpFactor		  = 1; // "jump_factor"
		Shape shape				  = Shape::Single; // "shape": "single", "double_height" or "double_length"
		bool  dynamicShape		  = false;		   // Shape depends on the position (random offset: bamboo...) ("dynamic_shape")
		std::string blockEntity;				   // Its block entity type ("block_entity": "minecraft:chest"...), empty if none
		// The block's Java class, superclasses and interfaces ("classes"): which vanilla behavior it has
		std::vector<std::string> classes;
	};
	// Per block state, from the game code
	struct StateProperties {
		uint8_t lightEmission		= 0;	 // 0-15 ("light_emission")
		bool	requiresCorrectTool = false; // Drops nothing without the right tool ("requires_correct_tool")
		bool	occludes			= false; // Full opaque block ("occludes")
		uint8_t lightBlock			= 0;	 // Light absorbed when passing through, 0-15 ("light_block"): air 0, leaves 1, stone 15
		bool	propagatesSkylightDown = true; // Sky light goes straight down through it without loss ("propagates_skylight_down")
		bool	blocksMotion		   = false; // "blocks_motion": has a collision and isn't a liquid (vanilla's legacy flag)
		bool	solid				   = false; // "solid": vanilla's legacySolid (isSolid)
		bool	replaceable			   = false; // "replaceable": placing a block replaces it (canBeReplaced)
		bool	randomTicking		   = false; // "random_ticking"
		bool	liquid				   = false; // "liquid": water, lava, bubble column (vanilla's legacy flag)
		bool	solidRender			   = false; // "solid_render": opaque full cube for rendering (isSolidRender)
		bool	useShapeForLightOcclusion = false; // "use_shape_for_light_occlusion": slabs, stairs, snow... block light by shape
		bool	ignitedByLava		   = false;	// "ignited_by_lava"
		bool	analogOutput		   = false; // "analog_output": comparators read it (hasAnalogOutputSignal)
		uint16_t occlusionShape		   = 0;		// "occlusion_shape": index in getCollisionShape's table
		bool	redstoneConductor	   = false; // "redstone_conductor"
		uint32_t faceSturdy			   = 0;		// "face_sturdy": bit direction * 3 + SupportType (FULL, CENTER, RIGID)
		uint16_t collisionShape		   = 0;		// "collision_shape": index in getCollisionShape()
		uint8_t	 fluid				   = 0;		// "fluid": minecraft:fluid id of its fluid state (0 = empty)
		uint8_t	 fluidAmount		   = 0;		// "fluid_amount": 1-8, 8 for sources
		bool	 fluidFalling		   = false; // "fluid_falling"
		uint8_t	 pushReaction		   = 0;		// "push_reaction": a PushReaction
	};
	// What a piston does to a block (PushReaction)
	enum class PushReaction : uint8_t { Normal = 0, Destroy = 1, Block = 2, Ignore = 3, PushOnly = 4 };
	enum class SupportType { Full = 0, Center = 1, Rigid = 2 };
	// Collision boxes, in block coordinates (0-1)
	struct Box {
		double minX, minY, minZ, maxX, maxY, maxZ;
	};

	// Where an item is worn or held for its stats to apply
	enum class EquipmentSlot { MainHand, OffHand, Head, Chest, Legs, Feet, Body, Saddle };

	// Per item, from the reports. Combat stats are bonuses added to the player's base values while the item is in
	// its equipment slot (a sword in the main hand, a chestplate on the chest)
	struct ItemProperties {
		int			  maxStackSize		  = 64;
		EquipmentSlot equipmentSlot		  = EquipmentSlot::MainHand;
		float		  attackDamage		  = 0; // "attack_damage": the hand does 1, a diamond sword adds 6
		float		  attackSpeed		  = 0; // "attack_speed": attacks per second bonus (base 4, a sword adds -2.4)
		float		  armor				  = 0;
		float		  armorToughness	  = 0; // "armor_toughness"
		float		  knockbackResistance = 0; // "knockback_resistance", 0-1
		bool		  fireResistant		  = false; // "fire_resistant": its item entity survives fire and lava (netherite...)
		bool		  canDestroyBlocksInCreative = true; // "can_destroy_blocks_in_creative": false for swords, the mace, the trident
		std::string	  craftingRemainder;		   // "crafting_remainder": what stays after crafting with it (buckets...)
		// "tool_rules": the first rule matching a block with correct_for_drops set decides whether it drops
		struct ToolRule {
			std::vector<bool> blocks; // By block id
			int				  correctForDrops = -1; // 1, 0, or -1 when the rule doesn't say
		};
		std::vector<ToolRule> toolRules;
	};

	struct Dimension {
		int minY;
		int height;
	};

	struct RegistryTags {
		std::string										  registry;
		std::vector<std::pair<std::string, std::vector<int>>> tags; // Tag name -> network ids
	};

	void load(const std::filesystem::path& directory);
	// The folder it was loaded from (other game data files live there too)
	const std::filesystem::path& getDirectory() const { return _directory; }

	const std::string& getVersionName() const { return _versionName; }
	int				   getProtocolVersion() const { return _protocolVersion; }
	int				   getDataVersion() const { return _dataVersion; }

	// Returns -1 for an unknown registry or entry
	int getStaticId(const std::string& registry, const std::string& entry) const;
	// Name of an entry of a static registry, "" if unknown
	const std::string& getStaticName(const std::string& registry, int id) const;
	int getSyncedId(const std::string& registry, const std::string& entry) const;

	const std::vector<Registry>&	 getSyncedRegistries() const { return _syncedRegistries; }
	const std::vector<RegistryTags>& getTags() const { return _tags; }

	// Block states, as found in chunk palettes. Returns -1 for an unknown block or property combination
	int getDefaultBlockState(const std::string& block) const;
	int getBlockState(const std::string& block, const std::map<std::string, std::string>& properties) const;
	// Block state as text, "minecraft:oak_log[axis=y]" or "minecraft:stone", and back
	int				   getBlockStateFromName(const std::string& name) const;
	const std::string& getBlockStateName(int stateId) const { return _blockStateNames.at(stateId); }
	int				   getBlockStateCount() const { return static_cast<int>(_blockStateNames.size()); }
	// Number of blocks (minecraft:block registry)
	size_t getBlockCount() const { return _staticRegistries.at("minecraft:block").entries.size(); }

	// Block states compiled for the game logic (fast property access)
	const BlockRegistry& getBlocks() const { return _blocks; }

	// Block (minecraft:block registry id) a state belongs to
	int					   getBlockOfState(int stateId) const { return _stateBlocks.at(stateId); }
	const BlockProperties& getBlockProperties(int stateId) const { return _blockProperties.at(_stateBlocks.at(stateId)); }
	const StateProperties& getStateProperties(int stateId) const { return _stateProperties.at(stateId); }
	float				   getDestroyTime(int stateId) const { return getBlockProperties(stateId).destroyTime; }
	// Whether the face of this side can support a block (torch, ladder...), vanilla's isFaceSturdy. direction: Direction id
	bool isFaceSturdy(int stateId, int direction, SupportType type) const {
		return _stateProperties[stateId].faceSturdy >> (direction * 3 + static_cast<int>(type)) & 1;
	}
	const std::vector<Box>& getCollisionShape(int stateId) const { return _collisionShapes[_stateProperties[stateId].collisionShape]; }
	const std::vector<Box>& getOcclusionShape(int stateId) const { return _collisionShapes[_stateProperties[stateId].occlusionShape]; }
	// Whether a block's class is (or extends, or implements) this vanilla class, e.g. "DoorBlock"
	bool isInstanceOf(int blockId, const std::string& javaClass) const;
	// Same state with one property changed, -1 if the block has no such property/value
	int withProperty(int stateId, const std::string& property, const std::string& value) const;
	// Value of a property of a state, "" if it has none
	std::string getProperty(int stateId, const std::string& property) const;

	// Default state of the block an item places, -1 for items that aren't blocks
	int getPlacedBlockState(int itemId) const;
	// nullptr for an unknown item id
	const ItemProperties* getItemProperties(int itemId) const;
	// Item.isCorrectToolForDrops (the tool component): whether mining this state with this item drops it
	bool isCorrectToolForDrops(int itemId, int stateId) const;

	// Whether an entry (id in its registry) is in a tag, e.g. isInTag("minecraft:block", "minecraft:replaceable", blockId)
	bool isInTag(const std::string& registry, const std::string& tag, int entryId) const;
	// A block tag as a table by block id, for game logic that checks it often (isInTag builds a string each time)
	std::vector<bool> blockTag(const std::string& tag) const;

	// nullptr for an unknown dimension type
	const Dimension* getDimension(const std::string& name) const;

  private:
	std::filesystem::path _directory;
	std::string			  _versionName;
	int			_protocolVersion = 0;
	int			_dataVersion	 = 0;

	std::unordered_map<std::string, Registry> _staticRegistries;
	std::vector<Registry>					  _syncedRegistries;
	std::unordered_map<std::string, size_t>	  _syncedIndex;
	std::vector<RegistryTags>				  _tags;

	std::unordered_map<std::string, int> _defaultBlockStates;
	std::unordered_map<std::string, int> _blockStates; // Key: blockStateKey()
	std::vector<std::string>			 _blockStateNames;

	std::vector<int>	_stateBlocks;
	BlockRegistry		_blocks;
	std::vector<BlockProperties> _blockProperties;
	std::vector<StateProperties> _stateProperties;
	std::vector<std::vector<Box>> _collisionShapes;
	std::vector<int>	_itemPlacedStates;
	std::vector<ItemProperties> _itemProperties;
	std::unordered_map<std::string, std::unordered_set<int>> _tagSets; // "registry#tag" -> ids

	std::unordered_map<std::string, Dimension> _dimensions;

	void			   addBlockState(const std::string& key, int id);
	void			   applyOverrides(const std::filesystem::path& file);
	void			   setBlockProperty(const std::string& block, const std::string& property, const nlohmann::ordered_json& value);
	void			   setItemProperty(const std::string& item, const std::string& property, const nlohmann::ordered_json& value);
	static std::string blockStateKey(const std::string& block, const std::map<std::string, std::string>& properties);
	const Registry*	   findRegistry(const std::string& registry) const;
};

#endif
