#ifndef GAME_DATA_HPP
#define GAME_DATA_HPP

#include <cstdint>
#include <filesystem>

#include "data/BlockRegistry.hpp"
#include "lib/json.hpp"
#include <map>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

// Version-specific game data loaded at startup from gamedata/ (generated by tools/update_gamedata.py), then
// gamedata/overrides.json (written by hand) applied on top:
//   {
//     "blocks":      { "minecraft:obsidian": { "destroy_time": 10, "light_emission": 7 },
//                      "minecraft:rose_bush": { "shape": "single" } },
//     "items":       { "minecraft:diamond_sword": { "attack_damage": 10 } },
//     "block_items": { "minecraft:stick": "minecraft:torch" }
//   }
// Block keys: any BlockProperties or StateProperties field below, by its JSON name (state ones apply to every state).
// Item keys: any ItemProperties field below, by its JSON name.
//
// Static registries (block, item, entity_type...) have ids fixed in the client.
// Synced registries (biome, dimension_type, enchantment...) are sent in Registry Data: an entry's id is its position in that packet.
class GameData {
  public:
	struct Registry {
		std::string							 name;
		std::vector<std::string>			 entries; // Index == network id
		std::unordered_map<std::string, int> ids;
	};

	// Blocks spanning two positions: one state per position, linked by a property
	enum class Shape {
		Single,
		DoubleHeight, // half=lower below, half=upper above (doors, tall plants)
		DoubleLength  // part=foot, part=head one block further in the facing direction (beds)
	};

	// Per block, from the game code
	struct BlockProperties {
		float destroyTime		  = 0; // Seconds to break by hand; -1 = unbreakable ("destroy_time")
		float explosionResistance = 0; // "explosion_resistance"
		float friction			  = 0.6f;
		float speedFactor		  = 1; // Walking speed multiplier ("speed_factor": soul sand, honey)
		float jumpFactor		  = 1; // "jump_factor"
		Shape shape				  = Shape::Single; // "shape": "single", "double_height" or "double_length"
	};
	// Per block state, from the game code
	struct StateProperties {
		uint8_t lightEmission		= 0;	 // 0-15 ("light_emission")
		bool	requiresCorrectTool = false; // Drops nothing without the right tool ("requires_correct_tool")
		bool	occludes			= false; // Full opaque block ("occludes")
		uint8_t lightBlock			= 0;	 // Light absorbed when passing through, 0-15 ("light_block"): air 0, leaves 1, stone 15
		bool	propagatesSkylightDown = true; // Sky light goes straight down through it without loss ("propagates_skylight_down")
	};

	// Where an item is worn or held for its stats to apply
	enum class EquipmentSlot { MainHand, OffHand, Head, Chest, Legs, Feet, Body, Saddle };

	// Per item, from the reports. Combat stats are bonuses added to the player's base values while the item is in
	// its equipment slot (a sword in the main hand, a chestplate on the chest)
	struct ItemProperties {
		int			  maxStackSize		  = 64;
		EquipmentSlot equipmentSlot		  = EquipmentSlot::MainHand;
		float		  attackDamage		  = 0; // "attack_damage": the hand does 1, a diamond sword adds 6
		float		  attackSpeed		  = 0; // "attack_speed": attacks per second bonus (base 4, a sword adds -2.4)
		float		  armor				  = 0;
		float		  armorToughness	  = 0; // "armor_toughness"
		float		  knockbackResistance = 0; // "knockback_resistance", 0-1
	};

	struct Dimension {
		int minY;
		int height;
	};

	struct RegistryTags {
		std::string										  registry;
		std::vector<std::pair<std::string, std::vector<int>>> tags; // Tag name -> network ids
	};

	void load(const std::filesystem::path& directory);

	const std::string& getVersionName() const { return _versionName; }
	int				   getProtocolVersion() const { return _protocolVersion; }
	int				   getDataVersion() const { return _dataVersion; }

	// Returns -1 for an unknown registry or entry
	int getStaticId(const std::string& registry, const std::string& entry) const;
	int getSyncedId(const std::string& registry, const std::string& entry) const;

	const std::vector<Registry>&	 getSyncedRegistries() const { return _syncedRegistries; }
	const std::vector<RegistryTags>& getTags() const { return _tags; }

	// Block states, as found in chunk palettes. Returns -1 for an unknown block or property combination
	int getDefaultBlockState(const std::string& block) const;
	int getBlockState(const std::string& block, const std::map<std::string, std::string>& properties) const;
	// Block state as text, "minecraft:oak_log[axis=y]" or "minecraft:stone", and back
	int				   getBlockStateFromName(const std::string& name) const;
	const std::string& getBlockStateName(int stateId) const { return _blockStateNames.at(stateId); }
	int				   getBlockStateCount() const { return static_cast<int>(_blockStateNames.size()); }

	// Block states compiled for the game logic (fast property access)
	const BlockRegistry& getBlocks() const { return _blocks; }

	// Block (minecraft:block registry id) a state belongs to
	int					   getBlockOfState(int stateId) const { return _stateBlocks.at(stateId); }
	const BlockProperties& getBlockProperties(int stateId) const { return _blockProperties.at(_stateBlocks.at(stateId)); }
	const StateProperties& getStateProperties(int stateId) const { return _stateProperties.at(stateId); }
	float				   getDestroyTime(int stateId) const { return getBlockProperties(stateId).destroyTime; }
	// Same state with one property changed, -1 if the block has no such property/value
	int withProperty(int stateId, const std::string& property, const std::string& value) const;
	// Value of a property of a state, "" if it has none
	std::string getProperty(int stateId, const std::string& property) const;

	// Default state of the block an item places, -1 for items that aren't blocks
	int getPlacedBlockState(int itemId) const;
	// nullptr for an unknown item id
	const ItemProperties* getItemProperties(int itemId) const;

	// Whether an entry (id in its registry) is in a tag, e.g. isInTag("minecraft:block", "minecraft:replaceable", blockId)
	bool isInTag(const std::string& registry, const std::string& tag, int entryId) const;

	// nullptr for an unknown dimension type
	const Dimension* getDimension(const std::string& name) const;

  private:
	std::string _versionName;
	int			_protocolVersion = 0;
	int			_dataVersion	 = 0;

	std::unordered_map<std::string, Registry> _staticRegistries;
	std::vector<Registry>					  _syncedRegistries;
	std::unordered_map<std::string, size_t>	  _syncedIndex;
	std::vector<RegistryTags>				  _tags;

	std::unordered_map<std::string, int> _defaultBlockStates;
	std::unordered_map<std::string, int> _blockStates; // Key: blockStateKey()
	std::vector<std::string>			 _blockStateNames;

	std::vector<int>	_stateBlocks;
	BlockRegistry		_blocks;
	std::vector<BlockProperties> _blockProperties;
	std::vector<StateProperties> _stateProperties;
	std::vector<int>	_itemPlacedStates;
	std::vector<ItemProperties> _itemProperties;
	std::unordered_map<std::string, std::unordered_set<int>> _tagSets; // "registry#tag" -> ids

	std::unordered_map<std::string, Dimension> _dimensions;

	void			   addBlockState(const std::string& key, int id);
	void			   applyOverrides(const std::filesystem::path& file);
	void			   setBlockProperty(const std::string& block, const std::string& property, const nlohmann::ordered_json& value);
	void			   setItemProperty(const std::string& item, const std::string& property, const nlohmann::ordered_json& value);
	static std::string blockStateKey(const std::string& block, const std::map<std::string, std::string>& properties);
	const Registry*	   findRegistry(const std::string& registry) const;
};

#endif
