#ifndef PACKET_IDS_HPP
#define PACKET_IDS_HPP

// Generated by tools/update_gamedata.py for Minecraft 1.21.10 - do not modify

#include <cstdint>

namespace PacketId {
	namespace Handshake {
		namespace Serverbound {
			constexpr int32_t INTENTION = 0x00;
		}
	}
	namespace Status {
		namespace Clientbound {
			constexpr int32_t STATUS_RESPONSE = 0x00;
			constexpr int32_t PONG_RESPONSE = 0x01;
		}
		namespace Serverbound {
			constexpr int32_t STATUS_REQUEST = 0x00;
			constexpr int32_t PING_REQUEST = 0x01;
		}
	}
	namespace Login {
		namespace Clientbound {
			constexpr int32_t LOGIN_DISCONNECT = 0x00;
			constexpr int32_t HELLO = 0x01;
			constexpr int32_t LOGIN_FINISHED = 0x02;
			constexpr int32_t LOGIN_COMPRESSION = 0x03;
			constexpr int32_t CUSTOM_QUERY = 0x04;
			constexpr int32_t COOKIE_REQUEST = 0x05;
		}
		namespace Serverbound {
			constexpr int32_t HELLO = 0x00;
			constexpr int32_t KEY = 0x01;
			constexpr int32_t CUSTOM_QUERY_ANSWER = 0x02;
			constexpr int32_t LOGIN_ACKNOWLEDGED = 0x03;
			constexpr int32_t COOKIE_RESPONSE = 0x04;
		}
	}
	namespace Configuration {
		namespace Clientbound {
			constexpr int32_t COOKIE_REQUEST = 0x00;
			constexpr int32_t CUSTOM_PAYLOAD = 0x01;
			constexpr int32_t DISCONNECT = 0x02;
			constexpr int32_t FINISH_CONFIGURATION = 0x03;
			constexpr int32_t KEEP_ALIVE = 0x04;
			constexpr int32_t PING = 0x05;
			constexpr int32_t RESET_CHAT = 0x06;
			constexpr int32_t REGISTRY_DATA = 0x07;
			constexpr int32_t RESOURCE_PACK_POP = 0x08;
			constexpr int32_t RESOURCE_PACK_PUSH = 0x09;
			constexpr int32_t STORE_COOKIE = 0x0A;
			constexpr int32_t TRANSFER = 0x0B;
			constexpr int32_t UPDATE_ENABLED_FEATURES = 0x0C;
			constexpr int32_t UPDATE_TAGS = 0x0D;
			constexpr int32_t SELECT_KNOWN_PACKS = 0x0E;
			constexpr int32_t CUSTOM_REPORT_DETAILS = 0x0F;
			constexpr int32_t SERVER_LINKS = 0x10;
			constexpr int32_t CLEAR_DIALOG = 0x11;
			constexpr int32_t SHOW_DIALOG = 0x12;
			constexpr int32_t CODE_OF_CONDUCT = 0x13;
		}
		namespace Serverbound {
			constexpr int32_t CLIENT_INFORMATION = 0x00;
			constexpr int32_t COOKIE_RESPONSE = 0x01;
			constexpr int32_t CUSTOM_PAYLOAD = 0x02;
			constexpr int32_t FINISH_CONFIGURATION = 0x03;
			constexpr int32_t KEEP_ALIVE = 0x04;
			constexpr int32_t PONG = 0x05;
			constexpr int32_t RESOURCE_PACK = 0x06;
			constexpr int32_t SELECT_KNOWN_PACKS = 0x07;
			constexpr int32_t CUSTOM_CLICK_ACTION = 0x08;
			constexpr int32_t ACCEPT_CODE_OF_CONDUCT = 0x09;
		}
	}
	namespace Play {
		namespace Clientbound {
			constexpr int32_t BUNDLE_DELIMITER = 0x00;
			constexpr int32_t ADD_ENTITY = 0x01;
			constexpr int32_t ANIMATE = 0x02;
			constexpr int32_t AWARD_STATS = 0x03;
			constexpr int32_t BLOCK_CHANGED_ACK = 0x04;
			constexpr int32_t BLOCK_DESTRUCTION = 0x05;
			constexpr int32_t BLOCK_ENTITY_DATA = 0x06;
			constexpr int32_t BLOCK_EVENT = 0x07;
			constexpr int32_t BLOCK_UPDATE = 0x08;
			constexpr int32_t BOSS_EVENT = 0x09;
			constexpr int32_t CHANGE_DIFFICULTY = 0x0A;
			constexpr int32_t CHUNK_BATCH_FINISHED = 0x0B;
			constexpr int32_t CHUNK_BATCH_START = 0x0C;
			constexpr int32_t CHUNKS_BIOMES = 0x0D;
			constexpr int32_t CLEAR_TITLES = 0x0E;
			constexpr int32_t COMMAND_SUGGESTIONS = 0x0F;
			constexpr int32_t COMMANDS = 0x10;
			constexpr int32_t CONTAINER_CLOSE = 0x11;
			constexpr int32_t CONTAINER_SET_CONTENT = 0x12;
			constexpr int32_t CONTAINER_SET_DATA = 0x13;
			constexpr int32_t CONTAINER_SET_SLOT = 0x14;
			constexpr int32_t COOKIE_REQUEST = 0x15;
			constexpr int32_t COOLDOWN = 0x16;
			constexpr int32_t CUSTOM_CHAT_COMPLETIONS = 0x17;
			constexpr int32_t CUSTOM_PAYLOAD = 0x18;
			constexpr int32_t DAMAGE_EVENT = 0x19;
			constexpr int32_t DEBUG_BLOCK_VALUE = 0x1A;
			constexpr int32_t DEBUG_CHUNK_VALUE = 0x1B;
			constexpr int32_t DEBUG_ENTITY_VALUE = 0x1C;
			constexpr int32_t DEBUG_EVENT = 0x1D;
			constexpr int32_t DEBUG_SAMPLE = 0x1E;
			constexpr int32_t DELETE_CHAT = 0x1F;
			constexpr int32_t DISCONNECT = 0x20;
			constexpr int32_t DISGUISED_CHAT = 0x21;
			constexpr int32_t ENTITY_EVENT = 0x22;
			constexpr int32_t ENTITY_POSITION_SYNC = 0x23;
			constexpr int32_t EXPLODE = 0x24;
			constexpr int32_t FORGET_LEVEL_CHUNK = 0x25;
			constexpr int32_t GAME_EVENT = 0x26;
			constexpr int32_t GAME_TEST_HIGHLIGHT_POS = 0x27;
			constexpr int32_t HORSE_SCREEN_OPEN = 0x28;
			constexpr int32_t HURT_ANIMATION = 0x29;
			constexpr int32_t INITIALIZE_BORDER = 0x2A;
			constexpr int32_t KEEP_ALIVE = 0x2B;
			constexpr int32_t LEVEL_CHUNK_WITH_LIGHT = 0x2C;
			constexpr int32_t LEVEL_EVENT = 0x2D;
			constexpr int32_t LEVEL_PARTICLES = 0x2E;
			constexpr int32_t LIGHT_UPDATE = 0x2F;
			constexpr int32_t LOGIN = 0x30;
			constexpr int32_t MAP_ITEM_DATA = 0x31;
			constexpr int32_t MERCHANT_OFFERS = 0x32;
			constexpr int32_t MOVE_ENTITY_POS = 0x33;
			constexpr int32_t MOVE_ENTITY_POS_ROT = 0x34;
			constexpr int32_t MOVE_MINECART_ALONG_TRACK = 0x35;
			constexpr int32_t MOVE_ENTITY_ROT = 0x36;
			constexpr int32_t MOVE_VEHICLE = 0x37;
			constexpr int32_t OPEN_BOOK = 0x38;
			constexpr int32_t OPEN_SCREEN = 0x39;
			constexpr int32_t OPEN_SIGN_EDITOR = 0x3A;
			constexpr int32_t PING = 0x3B;
			constexpr int32_t PONG_RESPONSE = 0x3C;
			constexpr int32_t PLACE_GHOST_RECIPE = 0x3D;
			constexpr int32_t PLAYER_ABILITIES = 0x3E;
			constexpr int32_t PLAYER_CHAT = 0x3F;
			constexpr int32_t PLAYER_COMBAT_END = 0x40;
			constexpr int32_t PLAYER_COMBAT_ENTER = 0x41;
			constexpr int32_t PLAYER_COMBAT_KILL = 0x42;
			constexpr int32_t PLAYER_INFO_REMOVE = 0x43;
			constexpr int32_t PLAYER_INFO_UPDATE = 0x44;
			constexpr int32_t PLAYER_LOOK_AT = 0x45;
			constexpr int32_t PLAYER_POSITION = 0x46;
			constexpr int32_t PLAYER_ROTATION = 0x47;
			constexpr int32_t RECIPE_BOOK_ADD = 0x48;
			constexpr int32_t RECIPE_BOOK_REMOVE = 0x49;
			constexpr int32_t RECIPE_BOOK_SETTINGS = 0x4A;
			constexpr int32_t REMOVE_ENTITIES = 0x4B;
			constexpr int32_t REMOVE_MOB_EFFECT = 0x4C;
			constexpr int32_t RESET_SCORE = 0x4D;
			constexpr int32_t RESOURCE_PACK_POP = 0x4E;
			constexpr int32_t RESOURCE_PACK_PUSH = 0x4F;
			constexpr int32_t RESPAWN = 0x50;
			constexpr int32_t ROTATE_HEAD = 0x51;
			constexpr int32_t SECTION_BLOCKS_UPDATE = 0x52;
			constexpr int32_t SELECT_ADVANCEMENTS_TAB = 0x53;
			constexpr int32_t SERVER_DATA = 0x54;
			constexpr int32_t SET_ACTION_BAR_TEXT = 0x55;
			constexpr int32_t SET_BORDER_CENTER = 0x56;
			constexpr int32_t SET_BORDER_LERP_SIZE = 0x57;
			constexpr int32_t SET_BORDER_SIZE = 0x58;
			constexpr int32_t SET_BORDER_WARNING_DELAY = 0x59;
			constexpr int32_t SET_BORDER_WARNING_DISTANCE = 0x5A;
			constexpr int32_t SET_CAMERA = 0x5B;
			constexpr int32_t SET_CHUNK_CACHE_CENTER = 0x5C;
			constexpr int32_t SET_CHUNK_CACHE_RADIUS = 0x5D;
			constexpr int32_t SET_CURSOR_ITEM = 0x5E;
			constexpr int32_t SET_DEFAULT_SPAWN_POSITION = 0x5F;
			constexpr int32_t SET_DISPLAY_OBJECTIVE = 0x60;
			constexpr int32_t SET_ENTITY_DATA = 0x61;
			constexpr int32_t SET_ENTITY_LINK = 0x62;
			constexpr int32_t SET_ENTITY_MOTION = 0x63;
			constexpr int32_t SET_EQUIPMENT = 0x64;
			constexpr int32_t SET_EXPERIENCE = 0x65;
			constexpr int32_t SET_HEALTH = 0x66;
			constexpr int32_t SET_HELD_SLOT = 0x67;
			constexpr int32_t SET_OBJECTIVE = 0x68;
			constexpr int32_t SET_PASSENGERS = 0x69;
			constexpr int32_t SET_PLAYER_INVENTORY = 0x6A;
			constexpr int32_t SET_PLAYER_TEAM = 0x6B;
			constexpr int32_t SET_SCORE = 0x6C;
			constexpr int32_t SET_SIMULATION_DISTANCE = 0x6D;
			constexpr int32_t SET_SUBTITLE_TEXT = 0x6E;
			constexpr int32_t SET_TIME = 0x6F;
			constexpr int32_t SET_TITLE_TEXT = 0x70;
			constexpr int32_t SET_TITLES_ANIMATION = 0x71;
			constexpr int32_t SOUND_ENTITY = 0x72;
			constexpr int32_t SOUND = 0x73;
			constexpr int32_t START_CONFIGURATION = 0x74;
			constexpr int32_t STOP_SOUND = 0x75;
			constexpr int32_t STORE_COOKIE = 0x76;
			constexpr int32_t SYSTEM_CHAT = 0x77;
			constexpr int32_t TAB_LIST = 0x78;
			constexpr int32_t TAG_QUERY = 0x79;
			constexpr int32_t TAKE_ITEM_ENTITY = 0x7A;
			constexpr int32_t TELEPORT_ENTITY = 0x7B;
			constexpr int32_t TEST_INSTANCE_BLOCK_STATUS = 0x7C;
			constexpr int32_t TICKING_STATE = 0x7D;
			constexpr int32_t TICKING_STEP = 0x7E;
			constexpr int32_t TRANSFER = 0x7F;
			constexpr int32_t UPDATE_ADVANCEMENTS = 0x80;
			constexpr int32_t UPDATE_ATTRIBUTES = 0x81;
			constexpr int32_t UPDATE_MOB_EFFECT = 0x82;
			constexpr int32_t UPDATE_RECIPES = 0x83;
			constexpr int32_t UPDATE_TAGS = 0x84;
			constexpr int32_t PROJECTILE_POWER = 0x85;
			constexpr int32_t CUSTOM_REPORT_DETAILS = 0x86;
			constexpr int32_t SERVER_LINKS = 0x87;
			constexpr int32_t WAYPOINT = 0x88;
			constexpr int32_t CLEAR_DIALOG = 0x89;
			constexpr int32_t SHOW_DIALOG = 0x8A;
		}
		namespace Serverbound {
			constexpr int32_t ACCEPT_TELEPORTATION = 0x00;
			constexpr int32_t BLOCK_ENTITY_TAG_QUERY = 0x01;
			constexpr int32_t BUNDLE_ITEM_SELECTED = 0x02;
			constexpr int32_t CHANGE_DIFFICULTY = 0x03;
			constexpr int32_t CHANGE_GAME_MODE = 0x04;
			constexpr int32_t CHAT_ACK = 0x05;
			constexpr int32_t CHAT_COMMAND = 0x06;
			constexpr int32_t CHAT_COMMAND_SIGNED = 0x07;
			constexpr int32_t CHAT = 0x08;
			constexpr int32_t CHAT_SESSION_UPDATE = 0x09;
			constexpr int32_t CHUNK_BATCH_RECEIVED = 0x0A;
			constexpr int32_t CLIENT_COMMAND = 0x0B;
			constexpr int32_t CLIENT_TICK_END = 0x0C;
			constexpr int32_t CLIENT_INFORMATION = 0x0D;
			constexpr int32_t COMMAND_SUGGESTION = 0x0E;
			constexpr int32_t CONFIGURATION_ACKNOWLEDGED = 0x0F;
			constexpr int32_t CONTAINER_BUTTON_CLICK = 0x10;
			constexpr int32_t CONTAINER_CLICK = 0x11;
			constexpr int32_t CONTAINER_CLOSE = 0x12;
			constexpr int32_t CONTAINER_SLOT_STATE_CHANGED = 0x13;
			constexpr int32_t COOKIE_RESPONSE = 0x14;
			constexpr int32_t CUSTOM_PAYLOAD = 0x15;
			constexpr int32_t DEBUG_SUBSCRIPTION_REQUEST = 0x16;
			constexpr int32_t EDIT_BOOK = 0x17;
			constexpr int32_t ENTITY_TAG_QUERY = 0x18;
			constexpr int32_t INTERACT = 0x19;
			constexpr int32_t JIGSAW_GENERATE = 0x1A;
			constexpr int32_t KEEP_ALIVE = 0x1B;
			constexpr int32_t LOCK_DIFFICULTY = 0x1C;
			constexpr int32_t MOVE_PLAYER_POS = 0x1D;
			constexpr int32_t MOVE_PLAYER_POS_ROT = 0x1E;
			constexpr int32_t MOVE_PLAYER_ROT = 0x1F;
			constexpr int32_t MOVE_PLAYER_STATUS_ONLY = 0x20;
			constexpr int32_t MOVE_VEHICLE = 0x21;
			constexpr int32_t PADDLE_BOAT = 0x22;
			constexpr int32_t PICK_ITEM_FROM_BLOCK = 0x23;
			constexpr int32_t PICK_ITEM_FROM_ENTITY = 0x24;
			constexpr int32_t PING_REQUEST = 0x25;
			constexpr int32_t PLACE_RECIPE = 0x26;
			constexpr int32_t PLAYER_ABILITIES = 0x27;
			constexpr int32_t PLAYER_ACTION = 0x28;
			constexpr int32_t PLAYER_COMMAND = 0x29;
			constexpr int32_t PLAYER_INPUT = 0x2A;
			constexpr int32_t PLAYER_LOADED = 0x2B;
			constexpr int32_t PONG = 0x2C;
			constexpr int32_t RECIPE_BOOK_CHANGE_SETTINGS = 0x2D;
			constexpr int32_t RECIPE_BOOK_SEEN_RECIPE = 0x2E;
			constexpr int32_t RENAME_ITEM = 0x2F;
			constexpr int32_t RESOURCE_PACK = 0x30;
			constexpr int32_t SEEN_ADVANCEMENTS = 0x31;
			constexpr int32_t SELECT_TRADE = 0x32;
			constexpr int32_t SET_BEACON = 0x33;
			constexpr int32_t SET_CARRIED_ITEM = 0x34;
			constexpr int32_t SET_COMMAND_BLOCK = 0x35;
			constexpr int32_t SET_COMMAND_MINECART = 0x36;
			constexpr int32_t SET_CREATIVE_MODE_SLOT = 0x37;
			constexpr int32_t SET_JIGSAW_BLOCK = 0x38;
			constexpr int32_t SET_STRUCTURE_BLOCK = 0x39;
			constexpr int32_t SET_TEST_BLOCK = 0x3A;
			constexpr int32_t SIGN_UPDATE = 0x3B;
			constexpr int32_t SWING = 0x3C;
			constexpr int32_t TELEPORT_TO_ENTITY = 0x3D;
			constexpr int32_t TEST_INSTANCE_BLOCK_ACTION = 0x3E;
			constexpr int32_t USE_ITEM_ON = 0x3F;
			constexpr int32_t USE_ITEM = 0x40;
			constexpr int32_t CUSTOM_CLICK_ACTION = 0x41;
		}
	}
} // namespace PacketId

#endif
