#include "world/AnvilImporter.hpp"

#include "data/GameData.hpp"
#include "lib/compression.hpp"
#include "lib/nbtParser.hpp"
#include "logger.hpp"

#include <fstream>
#include <map>
#include <stdexcept>

namespace {
	constexpr size_t MAX_CHUNK_SIZE = 64 * 1024 * 1024;

	uint32_t readBigEndian32(const uint8_t* p) { return (p[0] << 24) | (p[1] << 16) | (p[2] << 8) | p[3]; }

	std::shared_ptr<nbt::TagCompound> compound(const nbt::TagCompound& parent, const std::string& key) {
		if (!parent.contains(key)) return nullptr;
		const auto* value = std::get_if<std::shared_ptr<nbt::TagCompound>>(&parent.at(key).data);
		return value ? *value : nullptr;
	}

	std::shared_ptr<nbt::TagList> list(const nbt::TagCompound& parent, const std::string& key) {
		if (!parent.contains(key)) return nullptr;
		const auto* value = std::get_if<std::shared_ptr<nbt::TagList>>(&parent.at(key).data);
		return value ? *value : nullptr;
	}

	std::vector<uint64_t> longArray(const nbt::TagCompound& parent, const std::string& key) {
		if (!parent.contains(key)) return {};
		const auto* value = std::get_if<nbt::TagLongArray>(&parent.at(key).data);
		if (!value) return {};
		return std::vector<uint64_t>(value->begin(), value->end());
	}
} // namespace

AnvilImporter::AnvilImporter(const std::filesystem::path& worldDirectory, const GameData& gameData, const ChunkStorage::Layout& layout)
	: _regionDirectory(worldDirectory / "region"), _gameData(gameData), _layout(layout) {
	_available = std::filesystem::is_directory(_regionDirectory);
}

std::unique_ptr<Chunk> AnvilImporter::load(int x, int z) {
	if (!_available) return nullptr;

	std::filesystem::path path = _regionDirectory / ("r." + std::to_string(x >> 5) + "." + std::to_string(z >> 5) + ".mca");
	std::ifstream		  file(path, std::ios::binary);
	if (!file) return nullptr;

	uint8_t location[4];
	file.seekg(((z & 31) * 32 + (x & 31)) * 4);
	if (!file.read(reinterpret_cast<char*>(location), 4)) return nullptr;
	uint32_t sectorOffset = (location[0] << 16) | (location[1] << 8) | location[2];
	if (sectorOffset == 0) return nullptr;

	uint8_t header[5];
	file.seekg(static_cast<std::streamoff>(sectorOffset) * 4096);
	if (!file.read(reinterpret_cast<char*>(header), 5)) return nullptr;
	uint32_t length		 = readBigEndian32(header);
	uint8_t	 compression = header[4];
	if (length <= 1 || length > MAX_CHUNK_SIZE) return nullptr;
	if (compression & 0x80) {
		g_logger->logGameInfo(WARN, "Chunk " + std::to_string(x) + "," + std::to_string(z) + " is stored outside the region file, skipped", "World");
		return nullptr;
	}

	std::vector<uint8_t> raw(length - 1);
	if (!file.read(reinterpret_cast<char*>(raw.data()), raw.size())) return nullptr;

	std::vector<uint8_t> data;
	switch (compression) {
	case 1:
		data = compression::inflateUnknownSize(raw.data(), raw.size(), true, MAX_CHUNK_SIZE);
		break;
	case 2:
		data = compression::inflateUnknownSize(raw.data(), raw.size(), false, MAX_CHUNK_SIZE);
		break;
	case 3:
		data = std::move(raw);
		break;
	default:
		g_logger->logGameInfo(WARN, "Unsupported compression " + std::to_string(compression) + " in " + path.string(), "World");
		return nullptr;
	}

	nbt::NBT				 nbtData = nbt::Parser().parse(data);
	const nbt::TagCompound& root	= nbtData.getRoot();

	// Chunks still being generated by vanilla are regenerated by our generator
	if (!root.contains("Status") || root.at("Status").get<nbt::TagString>() != "minecraft:full") return nullptr;

	auto chunk = std::make_unique<Chunk>(x, z, _layout.minY, _layout.sectionCount, *_layout.blockConfig, *_layout.biomeConfig, _layout.air,
										 _layout.defaultBiome);
	auto sections = list(root, "sections");
	if (!sections) return chunk;

	int minSection = _layout.minY >> 4;
	for (const nbt::Tag& sectionTag : sections->data) {
		const auto* sectionPtr = std::get_if<std::shared_ptr<nbt::TagCompound>>(&sectionTag.data);
		if (!sectionPtr) continue;
		const nbt::TagCompound& section = **sectionPtr;
		int						index	= section.at("Y").get<nbt::TagByte>() - minSection;
		if (index < 0 || index >= _layout.sectionCount) continue;
		ChunkSection& target = chunk->sections()[index];

		if (auto blockStates = compound(section, "block_states")) {
			std::vector<uint32_t> palette;
			if (auto entries = list(*blockStates, "palette")) {
				for (const nbt::Tag& entryTag : entries->data) {
					const nbt::TagCompound& entry = *entryTag.get<std::shared_ptr<nbt::TagCompound>>();
					std::string				name  = entry.at("Name").get<nbt::TagString>();
					std::map<std::string, std::string> properties;
					if (auto props = compound(entry, "Properties")) {
						for (const auto& [key, value] : *props) properties[key] = value.get<nbt::TagString>();
					}
					int id = _gameData.getBlockState(name, properties);
					if (id < 0) id = _gameData.getDefaultBlockState(name);
					if (id < 0) {
						// Block removed or renamed in this version
						if (_unknownBlocks++ == 0) g_logger->logGameInfo(WARN, "Unknown block " + name + " replaced by air (further ones not logged)", "World");
						id = static_cast<int>(_layout.air);
					}
					palette.push_back(static_cast<uint32_t>(id));
				}
			}
			if (!palette.empty()) {
				uint8_t bits	  = std::max<uint8_t>(4, PalettedContainer::bitsFor(static_cast<uint32_t>(palette.size())));
				target.blocks	  = PalettedContainer::fromPalette(*_layout.blockConfig, palette, palette.size() == 1 ? 0 : bits,
																   longArray(*blockStates, "data"));
			}
		}

		if (auto biomes = compound(section, "biomes")) {
			std::vector<uint32_t> palette;
			if (auto entries = list(*biomes, "palette")) {
				for (const nbt::Tag& entryTag : entries->data) {
					int id = _gameData.getSyncedId("minecraft:worldgen/biome", entryTag.get<nbt::TagString>());
					palette.push_back(id < 0 ? _layout.defaultBiome : static_cast<uint32_t>(id));
				}
			}
			if (!palette.empty()) {
				uint8_t bits  = PalettedContainer::bitsFor(static_cast<uint32_t>(palette.size()));
				target.biomes = PalettedContainer::fromPalette(*_layout.biomeConfig, palette, bits, longArray(*biomes, "data"));
			}
		}
	}

	// Saved in our format on the next autosave
	chunk->markModified();
	return chunk;
}

std::optional<AnvilImporter::Spawn> AnvilImporter::readSpawn(const std::filesystem::path& worldDirectory) {
	std::ifstream file(worldDirectory / "level.dat", std::ios::binary);
	if (!file) return std::nullopt;
	std::vector<uint8_t> compressed((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());

	try {
		std::vector<uint8_t> raw  = compression::inflateUnknownSize(compressed.data(), compressed.size(), true, MAX_CHUNK_SIZE);
		nbt::NBT			 level = nbt::Parser().parse(raw);
		auto				 data  = compound(level.getRoot(), "Data");
		if (!data) return std::nullopt;

		// 1.21.9+: "spawn": {pos: [I; x, y, z], ...}
		if (auto spawn = compound(*data, "spawn")) {
			const auto* pos = std::get_if<nbt::TagIntArray>(&spawn->at("pos").data);
			if (pos && pos->size() == 3) return Spawn{(*pos)[0], (*pos)[1], (*pos)[2]};
		}
		if (data->contains("SpawnX")) {
			return Spawn{data->at("SpawnX").get<nbt::TagInt>(), data->at("SpawnY").get<nbt::TagInt>(), data->at("SpawnZ").get<nbt::TagInt>()};
		}
	} catch (const std::exception& e) {
		g_logger->logGameInfo(WARN, "Cannot read level.dat: " + std::string(e.what()), "World");
	}
	return std::nullopt;
}
