#!/usr/bin/env python3
"""Generates docs/PACKETS_SUPPORTED.md and docs/PACKETS_MISSING.md.

    python3 tools/packet_status.py

Every packet of the version comes from include/network/PacketIds.hpp (generated by update_gamedata.py).
A packet counts as supported when src/ uses its constant (PacketId::<State>::<Direction>::<NAME>): sent for
clientbound packets, handled by the router for serverbound ones. Use the constants, not raw ids, for this to work.
"""
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "include" / "network" / "PacketIds.hpp"
DOCS = ROOT / "docs"
IGNORED_FILES = {"templateClientBoundPacket.cpp"}

STATES = ["Handshake", "Status", "Login", "Configuration", "Play"]
DIRECTIONS = {"Clientbound": "Serveur → client", "Serverbound": "Client → serveur"}


def read_packets():
    packets, state, direction, version = [], None, None, "?"
    for line in HEADER.read_text().splitlines():
        if m := re.search(r"for Minecraft (\S+)", line):
            version = m.group(1)
        if m := re.match(r"\t(?:namespace )?(\w+) \{", line):
            state = m.group(1)
        elif m := re.match(r"\t\tnamespace (\w+) \{", line):
            direction = m.group(1)
        elif m := re.search(r"constexpr int32_t (\w+) = (0x[0-9A-F]+);", line):
            packets.append((state, direction, m.group(1), m.group(2)))
    return packets, version


def find_usages():
    usages = defaultdict(set)
    for file in sorted((ROOT / "src").rglob("*.cpp")):
        if file.name in IGNORED_FILES:
            continue
        for m in re.finditer(r"PacketId::(\w+)::(\w+)::(\w+)", file.read_text()):
            usages[m.groups()].add(file.relative_to(ROOT).as_posix())
    return usages


def section(title, rows, header, render):
    out = [f"### {title}", ""]
    if not rows:
        return out + ["_Aucun._", ""]
    out += [header, "|" + "---|" * (header.count("|") - 1)]
    out += [render(r) for r in rows] + [""]
    return out


def main():
    packets, version = read_packets()
    usages = find_usages()
    DOCS.mkdir(exist_ok=True)

    supported = ["# Paquets gérés", "",
                 f"Minecraft {version}. Généré par `tools/packet_status.py` (`make packets`), ne pas modifier à la main.", ""]
    missing = ["# Paquets manquants", "",
               f"Minecraft {version}. Généré par `tools/packet_status.py` (`make packets`), ne pas modifier à la main.", ""]

    total = {"ok": 0, "missing": 0}
    for state in STATES:
        supported += [f"## {state}", ""]
        missing += [f"## {state}", ""]
        for direction, label in DIRECTIONS.items():
            rows = [p for p in packets if p[0] == state and p[1] == direction]
            if not rows:
                continue
            done = [p for p in rows if (p[0], p[1], p[2]) in usages]
            todo = [p for p in rows if (p[0], p[1], p[2]) not in usages]
            total["ok"] += len(done)
            total["missing"] += len(todo)
            supported += section(f"{label} ({len(done)}/{len(rows)})", done, "| Paquet | ID | Utilisé dans |",
                                 lambda p: f"| `{p[2]}` | {p[3]} | " + ", ".join(f"`{f}`" for f in sorted(usages[(p[0], p[1], p[2])])) + " |")
            missing += section(f"{label} ({len(todo)} manquants sur {len(rows)})", todo, "| Paquet | ID |",
                               lambda p: f"| `{p[2]}` | {p[3]} |")

    all_count = total["ok"] + total["missing"]
    summary = f"**{total['ok']} paquets gérés sur {all_count}** ({total['missing']} manquants)."
    supported.insert(4, summary + "\n")
    missing.insert(4, summary + "\n")
    (DOCS / "PACKETS_SUPPORTED.md").write_text("\n".join(supported))
    (DOCS / "PACKETS_MISSING.md").write_text("\n".join(missing))
    print(f"docs/PACKETS_SUPPORTED.md, docs/PACKETS_MISSING.md: {total['ok']}/{all_count} packets supported")


if __name__ == "__main__":
    main()
