name: clang-format

on:
    push:

jobs:
    clang-format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Run clang-format
              uses: jidicula/clang-format-action@v4.11.0
              with:
                  clang-format-version: "17"
                  check-path: "."
